// <auto-generated />
using System;
using DatabaseModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseModel.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    partial class ExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseModel.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PostIndex")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.BillModifierEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Guid");

                    b.ToTable("BillModifierEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BillModifierEntity");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.CurrencyEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CurrencySign")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("21ae3cd1-79bc-4f6c-b6b6-ec916298c269"),
                            Abbreviation = "USD",
                            CountryCode = "840",
                            CurrencySign = "$",
                            Name = "United States Dollar"
                        });
                });

            modelBuilder.Entity("DatabaseModel.Entities.JoinEntities.OrderToBillModifier", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillModifierId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderId", "BillModifierId");

                    b.HasIndex("BillModifierId");

                    b.ToTable("OrderToBillModifier");
                });

            modelBuilder.Entity("DatabaseModel.Entities.JoinEntities.ProductProductClassEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductClassId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ProductId", "ProductClassId");

                    b.HasIndex("ProductClassId");

                    b.ToTable("ProductProductClassEntity");
                });

            modelBuilder.Entity("DatabaseModel.Entities.MeasureUnitConversionEntity", b =>
                {
                    b.Property<Guid>("FromId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ToId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("FromId", "ToId");

                    b.HasIndex("ToId");

                    b.ToTable("MeasureUnitConversions");
                });

            modelBuilder.Entity("DatabaseModel.Entities.MeasureUnitEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.ToTable("MeasureUnits");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Order.OrderEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Bill")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Order.OrderTransactionEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TransactionStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Guid");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTransactions");
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductClassAttributeEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssociatedClassId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("Mandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("ValueDataType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Guid");

                    b.HasIndex("AssociatedClassId");

                    b.HasIndex("Name", "AssociatedClassId")
                        .IsUnique();

                    b.ToTable("ProductClassAttributes");
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductClassAttributeValueEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductClassAttributeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.HasIndex("ProductClassAttributeId");

                    b.HasIndex("ProductId", "ProductClassAttributeId")
                        .IsUnique();

                    b.ToTable("ProductClassAttributeValues");
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductClassEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Name");

                    b.ToTable("ProductClasses");
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Seller.SellerEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("DatabaseModel.Entities.UserDeviceLoginEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Guid");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceLogins");
                });

            modelBuilder.Entity("DatabaseModel.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("6983a033-e12d-4c8d-a2df-f03df3ba4164"),
                            PasswordHash = "5qBbtpOnndwMpBQMy7wHKNn+X7apP6uL2tbWCMF5W9kB1kXbfX4PQ/e6M7NZg9ikX5D87BaRNKAw21GeiWdm7E5A0cY2ZHm/+uVDhX69v/jPR8ZxsYWff6uI33BNEjEczgMHFGVPNeexChDwSOkdU2DxwnLvOvkdpyQ41NxU0/k=.r4jOHK32cleYtwBxveLsnQ==",
                            Role = "Administrator",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DatabaseModel.Entities.ValueChangeRequestEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreviousValue")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ProductClassAttributeValueId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ResolutionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Guid");

                    b.HasIndex("ProductClassAttributeValueId");

                    b.HasIndex("SenderId");

                    b.ToTable("ValueChangeRequests");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.SellerBillModifierEntity", b =>
                {
                    b.HasBaseType("DatabaseModel.Entities.Currency.BillModifierEntity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("SellerBillModifierEntity");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.UserBillModifierEntity", b =>
                {
                    b.HasBaseType("DatabaseModel.Entities.Currency.BillModifierEntity");

                    b.HasIndex("OwnerId")
                        .HasName("IX_BillModifierEntity_OwnerId1");

                    b.HasDiscriminator().HasValue("UserBillModifierEntity");
                });

            modelBuilder.Entity("DatabaseModel.Entities.JoinEntities.OrderToBillModifier", b =>
                {
                    b.HasOne("DatabaseModel.Entities.Currency.BillModifierEntity", "BillModifier")
                        .WithMany()
                        .HasForeignKey("BillModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.Order.OrderEntity", "Order")
                        .WithMany("Modifiers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.JoinEntities.ProductProductClassEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.ProductClassEntity", "ProductClass")
                        .WithMany("ProductProductClasses")
                        .HasForeignKey("ProductClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.ProductEntity", "Product")
                        .WithMany("ProductProductClasses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.MeasureUnitConversionEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.MeasureUnitEntity", "From")
                        .WithMany("Conversions")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.MeasureUnitEntity", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.Order.OrderEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.AddressEntity", "Address")
                        .WithOne()
                        .HasForeignKey("DatabaseModel.Entities.Order.OrderEntity", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.UserEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.ProductEntity", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.Order.OrderTransactionEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.Currency.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.Order.OrderEntity", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductClassAttributeEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.ProductClassEntity", "AssociatedClass")
                        .WithMany("ProductClassAttributes")
                        .HasForeignKey("AssociatedClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductClassAttributeValueEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.ProductClassAttributeEntity", "ProductClassAttribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductClassAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.ProductEntity", "Product")
                        .WithMany("ProductClassAttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.ProductEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.Seller.SellerEntity", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Seller.SellerEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.AddressEntity", "Address")
                        .WithOne()
                        .HasForeignKey("DatabaseModel.Entities.Seller.SellerEntity", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.UserDeviceLoginEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.UserEntity", "User")
                        .WithMany("UserDeviceLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.UserEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.Seller.SellerEntity", "Seller")
                        .WithMany("Users")
                        .HasForeignKey("SellerId");
                });

            modelBuilder.Entity("DatabaseModel.Entities.ValueChangeRequestEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.ProductClassAttributeValueEntity", "AttributeValue")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("ProductClassAttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.Seller.SellerEntity", "Sender")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.SellerBillModifierEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.Seller.SellerEntity", "Seller")
                        .WithMany("Discounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseModel.Entities.ProductEntity", "Product")
                        .WithOne("Discount")
                        .HasForeignKey("DatabaseModel.Entities.Currency.SellerBillModifierEntity", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseModel.Entities.Currency.UserBillModifierEntity", b =>
                {
                    b.HasOne("DatabaseModel.Entities.UserEntity", "User")
                        .WithMany("Discounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
